// import { Business, Review, User, Category } from '@/types'

// export const categories: Category[] = [
//   { id: 'food', name: 'Food & Groceries', icon: '🍲', count: 142, color: '#1D9E75' },
//   { id: 'fashion', name: 'Fashion & Fabric', icon: '👗', count: 89, color: '#BA7517' },
//   { id: 'beauty', name: 'Beauty & Hair', icon: '💆', count: 76, color: '#7C3AED' },
//   { id: 'music', name: 'Music & Arts', icon: '🎵', count: 34, color: '#DB2777' },
//   { id: 'herbs', name: 'Herbs & Wellness', icon: '🌿', count: 28, color: '#065F46' },
//   { id: 'crafts', name: 'Crafts & Decor', icon: '🏺', count: 51, color: '#92400E' },
//   { id: 'restaurant', name: 'Restaurants', icon: '🍽️', count: 98, color: '#DC2626' },
//   { id: 'services', name: 'Services', icon: '🛠️', count: 63, color: '#1D4ED8' },
// ]

// export const businesses: Business[] = [
//   {
//     id: '1',
//     name: 'Mama Titi African Kitchen',
//     category: 'restaurant',
//     subcategory: 'West African Cuisine',
//     description: 'Authentic Nigerian and West African dishes made with imported spices and traditional recipes. From jollof rice to egusi soup — taste home in Houston.',
//     address: '4821 Main St',
//     city: 'Houston',
//     state: 'TX',
//     zip: '77002',
//     phone: '+1 (713) 555-0192',
//     email: 'hello@mamatiti.com',
//     website: 'https://mamatiti.com',
//     hours: { Mon: '10am–9pm', Tue: '10am–9pm', Wed: '10am–9pm', Thu: '10am–9pm', Fri: '10am–11pm', Sat: '9am–11pm', Sun: '11am–8pm' },
//     images: ['https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=800', 'https://images.unsplash.com/photo-1567364816519-cbc9c4ffe1eb?w=800'],
//     coverImage: 'https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=800',
//     rating: 4.8,
//     reviewCount: 124,
//     priceRange: '$$',
//     tags: ['Jollof Rice', 'Egusi Soup', 'Suya', 'Nigerian', 'Catering'],
//     country: 'Nigeria',
//     lat: 29.7604,
//     lng: -95.3698,
//     verified: true,
//     premium: true,
//     featured: true,
//     products: [
//       { id: 'p1', name: 'Jollof Rice (Party Size)', price: 45, description: 'Smoky party jollof rice for 4–6 people', image: 'https://images.unsplash.com/photo-1567364816519-cbc9c4ffe1eb?w=400', available: true },
//       { id: 'p2', name: 'Egusi Soup + Fufu', price: 22, description: 'Fresh egusi with assorted meats', image: 'https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?w=400', available: true },
//       { id: 'p3', name: 'Suya Platter', price: 18, description: 'Spiced beef suya with sliced onions', image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=400', available: true },
//     ],
//     ownerId: 'u2',
//   },
//   {
//     id: '2',
//     name: 'Ankara Palace Houston',
//     category: 'fashion',
//     subcategory: 'African Fabric & Fashion',
//     description: 'The largest collection of authentic ankara, kente, aso-oke and adire fabrics in Houston. Custom tailoring available. We ship nationwide.',
//     address: '2210 Westheimer Rd',
//     city: 'Houston',
//     state: 'TX',
//     zip: '77098',
//     phone: '+1 (713) 555-0348',
//     email: 'shop@ankarapalace.com',
//     hours: { Mon: 'Closed', Tue: '10am–7pm', Wed: '10am–7pm', Thu: '10am–7pm', Fri: '10am–8pm', Sat: '9am–8pm', Sun: '12pm–6pm' },
//     images: ['https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=800'],
//     coverImage: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=800',
//     rating: 4.9,
//     reviewCount: 87,
//     priceRange: '$$',
//     tags: ['Ankara', 'Kente', 'Aso-oke', 'Tailoring', 'Custom Design'],
//     country: 'Nigeria',
//     lat: 29.7395,
//     lng: -95.4138,
//     verified: true,
//     premium: true,
//     featured: true,
//     products: [
//       { id: 'p4', name: 'Ankara Fabric (6 yards)', price: 35, description: 'Premium Holland wax print fabric', image: 'https://images.unsplash.com/photo-1558769132-cb1aea458c5e?w=400', available: true },
//       { id: 'p5', name: 'Kente Cloth', price: 120, description: 'Hand-woven Ghanaian kente cloth', image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400', available: true },
//     ],
//     ownerId: 'u3',
//   },
//   {
//     id: '3',
//     name: 'Adunola African Market',
//     category: 'food',
//     subcategory: 'African Grocery',
//     description: 'Your one-stop shop for African groceries in Houston. We carry over 500 products including palm oil, crayfish, yams, plantains, and imported Nigerian seasoning cubes.',
//     address: '8903 Cullen Blvd',
//     city: 'Houston',
//     state: 'TX',
//     zip: '77051',
//     phone: '+1 (713) 555-0774',
//     email: 'contact@adunola.com',
//     hours: { Mon: '8am–9pm', Tue: '8am–9pm', Wed: '8am–9pm', Thu: '8am–9pm', Fri: '8am–10pm', Sat: '7am–10pm', Sun: '9am–8pm' },
//     images: ['https://images.unsplash.com/photo-1542838132-92c53300491e?w=800'],
//     coverImage: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=800',
//     rating: 4.6,
//     reviewCount: 213,
//     priceRange: '$',
//     tags: ['Palm Oil', 'Yam', 'Crayfish', 'Seasoning', 'Plantain', 'Stockfish'],
//     country: 'Nigeria',
//     lat: 29.6774,
//     lng: -95.3827,
//     verified: true,
//     premium: false,
//     featured: false,
//     products: [
//       { id: 'p6', name: 'Red Palm Oil (5L)', price: 28, description: 'Unrefined Nigerian red palm oil', image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400', available: true },
//     ],
//     ownerId: 'u4',
//   },
//   {
//     id: '4',
//     name: 'Queens Braid & Beauty',
//     category: 'beauty',
//     subcategory: 'African Hair Salon',
//     description: 'Expert African hair braiding, locs, weaves, and natural hair care. Specialising in knotless braids, Senegalese twists, and faux locs. Walk-ins welcome.',
//     address: '5544 Richmond Ave',
//     city: 'Houston',
//     state: 'TX',
//     zip: '77056',
//     phone: '+1 (713) 555-0612',
//     email: 'queens@braidshouston.com',
//     hours: { Mon: '9am–7pm', Tue: '9am–7pm', Wed: '9am–7pm', Thu: '9am–8pm', Fri: '9am–8pm', Sat: '8am–8pm', Sun: '10am–5pm' },
//     images: ['https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=800'],
//     coverImage: 'https://images.unsplash.com/photo-1522338242992-e1a54906a8da?w=800',
//     rating: 4.7,
//     reviewCount: 158,
//     priceRange: '$$',
//     tags: ['Knotless Braids', 'Senegalese Twists', 'Locs', 'Natural Hair', 'Weaves'],
//     country: 'Ghana',
//     lat: 29.7369,
//     lng: -95.4613,
//     verified: true,
//     premium: true,
//     featured: false,
//     ownerId: 'u5',
//   },
//   {
//     id: '5',
//     name: 'Naija Spice & Herb Shop',
//     category: 'herbs',
//     subcategory: 'African Herbs & Wellness',
//     description: 'Traditional African herbs, herbal teas, and wellness products. Sourced directly from trusted farms in Nigeria, Ghana, and Cameroon.',
//     address: '1204 Beechnut St',
//     city: 'Houston',
//     state: 'TX',
//     zip: '77072',
//     phone: '+1 (713) 555-0989',
//     email: 'info@naijaspice.com',
//     hours: { Mon: '9am–6pm', Tue: '9am–6pm', Wed: '9am–6pm', Thu: '9am–6pm', Fri: '9am–7pm', Sat: '9am–7pm', Sun: 'Closed' },
//     images: ['https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800'],
//     coverImage: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800',
//     rating: 4.5,
//     reviewCount: 62,
//     priceRange: '$',
//     tags: ['Moringa', 'Bitter Leaf', 'Zobo', 'African Tea', 'Natural Remedies'],
//     country: 'Nigeria',
//     lat: 29.7052,
//     lng: -95.5635,
//     verified: false,
//     premium: false,
//     featured: false,
//   },
//   {
//     id: '6',
//     name: 'AfroBeats Music & Culture',
//     category: 'music',
//     subcategory: 'African Music Store',
//     description: 'Vinyl records, instruments, Afrobeats merchandise, and cultural items. DJ equipment hire available. We also host monthly listening parties.',
//     address: '3367 Westpark Dr',
//     city: 'Houston',
//     state: 'TX',
//     zip: '77005',
//     phone: '+1 (713) 555-0231',
//     email: 'beats@afrobeatshtx.com',
//     hours: { Mon: 'Closed', Tue: '12pm–8pm', Wed: '12pm–8pm', Thu: '12pm–8pm', Fri: '12pm–10pm', Sat: '11am–10pm', Sun: '12pm–6pm' },
//     images: ['https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800'],
//     coverImage: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800',
//     rating: 4.9,
//     reviewCount: 44,
//     priceRange: '$$',
//     tags: ['Vinyl', 'Afrobeats', 'DJ Equipment', 'Events', 'Instruments'],
//     country: 'Nigeria',
//     lat: 29.7205,
//     lng: -95.4230,
//     verified: true,
//     premium: false,
//     featured: true,
//   },
// ]

// export const reviews: Review[] = [
//   {
//     id: 'r1',
//     businessId: '1',
//     userId: 'u1',
//     userName: 'Chisom Okafor',
//     userAvatar: 'https://i.pravatar.cc/40?img=1',
//     rating: 5,
//     title: 'Best jollof in Houston, no debate!',
//     body: 'I moved from Lagos 3 years ago and have been searching for authentic jollof rice ever since. Mama Titi is the real deal — the smoky bottom, the tomato base, everything. The egusi soup is also incredible. I order every week now.',
//     date: '2025-04-12',
//     helpful: 34,
//     verified: true,
//   },
//   {
//     id: 'r2',
//     businessId: '1',
//     userId: 'u6',
//     userName: 'Adaeze Williams',
//     userAvatar: 'https://i.pravatar.cc/40?img=5',
//     rating: 5,
//     title: 'Catered our thanksgiving and it was a hit',
//     body: 'Mama Titi catered our family thanksgiving and everyone — including our American family members — could not stop eating. The suya was the star of the show. Highly recommend for events.',
//     date: '2025-03-28',
//     helpful: 21,
//     verified: true,
//   },
//   {
//     id: 'r3',
//     businessId: '1',
//     userId: 'u7',
//     userName: 'Emeka Eze',
//     userAvatar: 'https://i.pravatar.cc/40?img=8',
//     rating: 4,
//     title: 'Great food, parking can be tricky',
//     body: 'The food is excellent — I had the pepper soup and it was deeply comforting. The only issue is finding parking on weekend evenings. Worth the effort though.',
//     date: '2025-03-01',
//     helpful: 8,
//     verified: false,
//   },
//   {
//     id: 'r4',
//     businessId: '2',
//     userId: 'u8',
//     userName: 'Folake Adeyemi',
//     userAvatar: 'https://i.pravatar.cc/40?img=9',
//     rating: 5,
//     title: 'Nothing comes close in Houston',
//     body: 'I have been coming here for 4 years. The fabric quality is consistently excellent and the tailoring team understands African fashion properly. My aso-ebi for my sister\'s wedding came out perfectly.',
//     date: '2025-04-20',
//     helpful: 42,
//     verified: true,
//   },
//   {
//     id: 'r5',
//     businessId: '3',
//     userId: 'u9',
//     userName: 'Ngozi Ibeh',
//     userAvatar: 'https://i.pravatar.cc/40?img=3',
//     rating: 4,
//     title: 'Great selection, fair prices',
//     body: 'Adunola has almost everything I need for Nigerian cooking. The palm oil and crayfish are always fresh. Sometimes stockfish runs out but they restock quickly.',
//     date: '2025-04-08',
//     helpful: 15,
//     verified: true,
//   },
// ]

// export const mockUser: User = {
//   id: 'u1',
//   name: 'Chisom Okafor',
//   email: 'chisom@example.com',
//   avatar: 'https://i.pravatar.cc/40?img=1',
//   role: 'owner',
//   businessId: '1',
//   joinedDate: '2024-01-15',
//   reviewCount: 7,
// }

// export function getBusinessById(id: string): Business | undefined {
//   return businesses.find(b => b.id === id)
// }

// export function getReviewsByBusiness(businessId: string): Review[] {
//   return reviews.filter(r => r.businessId === businessId)
// }

// export function searchBusinesses(query: string, category?: string, city?: string): Business[] {
//   return businesses.filter(b => {
//     const matchesQuery = !query || 
//       b.name.toLowerCase().includes(query.toLowerCase()) ||
//       b.description.toLowerCase().includes(query.toLowerCase()) ||
//       b.tags.some(t => t.toLowerCase().includes(query.toLowerCase())) ||
//       b.subcategory.toLowerCase().includes(query.toLowerCase())
//     const matchesCategory = !category || b.category === category
//     const matchesCity = !city || b.city.toLowerCase().includes(city.toLowerCase())
//     return matchesQuery && matchesCategory && matchesCity
//   })
// }